#!/bin/sh
set -e

BUCKET="boulders.iff.io"

npm run build

# Upload all files to the bucket with no cache-control.
gsutil -m -h 'Cache-Control: public, max-age=86400' rsync -cR \
    assets/ gs://$BUCKET
gsutil -m -h 'Cache-Control: public, max-age=86400' rsync -cR \
    dist/ gs://$BUCKET

# Now change the cache-control header of all files except HTML.
gsutil -m setmeta -h 'Cache-Control: no-cache, no-store, must-revalidate' \
    gs://$BUCKET/**/*.html gs://$BUCKET/**/*.js

echo `git rev-parse HEAD` > version
gsutil -m -h 'Cache-Control: no-cache, no-store, must-revalidate' cp \
    version gs://$BUCKET/version

rm version
